### PR TITLE
Add new mod: Cleric.ArtifactLaser

### LINKED ISSUE #365: Artifact Laser
### Your Discord Name

coderCleric

### Mod uniqueName

Cleric.ArtifactLaser

### Mod name

Artifact Laser

### GitHub repository URL

https://github.com/coderCleric/artifact_laser

### Parent uniqueName

_No response_

### Utility mod

_No response_

### Alpha Mod

_No response_

### PR DESCRIPTION
**Pull request by Raicuparta**
Closes #365
https://github.com/coderCleric/artifact_laser

### CODE REVIEW

**Comment by coderCleric** [comment]
It seems like I have the option to add an approving review, am I supposed to do that or wait for somebody who runs the database to do so?

**Comment by MegaPiggy** [comment]
Just wait for Raicuparta to approve it and then it will be added to db

**Comment by coderCleric** [comment]
Good to know, thanks!

**Review by xen-42 — APPROVED** [review]

**Comment by xen-42** [comment]
Or you wait for me to approve it

**Pull request merged**
