### PR TITLE
Add new mod: Joooosh.SurviveTheSupernova

### LINKED ISSUE #263: Survive the Supernova
### Mod uniqueName

Joooosh.SurviveTheSupernova

### Mod name

Survive the Supernova

### GitHub repository URL

https://github.com/joshua-smith98/OW-SurviveTheSupernova

### Parent uniqueName

_No response_

### Utility mod

_No response_

### PR DESCRIPTION
**Pull request by Raicuparta**
Closes #263
https://github.com/joshua-smith98/OW-SurviveTheSupernova

### CODE REVIEW

**Review by xen-42 — APPROVED** [review]

**Comment by xen-42** [comment]
Btw Josh you should make the "About" thing more informative since it's what will be displayed on the website and in the mod manager. I'd make an issue about it on your repo but since you forked the template instead of clicking the "use template" thingy I can't open one. Try doing that instead of forking next time if you make more!

**Comment by Raicuparta** [comment]
> 

@joshua-smith98 this was for you

**Comment by Raicuparta** [comment]
> Btw Josh you should make the "About" thing more informative since it's what will be displayed on the website and in the mod manager. I'd make an issue about it on your repo but since you forked the template instead of clicking the "use template" thingy I can't open one. Try doing that instead of forking next time if you make more!

@joshua-smith98 just pinging you about xen's message

**Comment by joshua-smith98** [comment]
Ah sorry, I must've missed this, I'm relatively new to Github. I will use the "use template" button next time thanks!
I've also changed the description. Thanks for the tips!

**Pull request merged**
